services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NAME=${NAME}
        - EMAIL=${EMAIL}
        - NPM_TOKEN=${NPM_TOKEN}
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh:ro
      - node_modules:/app/node_modules
      - /run/host-services/ssh-auth.sock:/tmp/agent.sock
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock
volumes:
  node_modules:
